name: muscalnc-ucvm-ci

on:
  push:
    branches: [ main ]
##    branches: [ foofoo ]

jobs:
  muscalnc-build-ucvm-linux:
    runs-on: ubuntu-latest
#    needs: [muscalnc-build-ucvm-mac]
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/muscalnc/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/muscalnc/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v4
      with: 
        repository: 'SCECcode/UCVM'
##        ref: testMei
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'muscalnc'
         target-model: 'muscalnc'
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock muscalnc away
      run: (rm -rf $RUNNER_WORKSPACE/muscalnc/ucvm/work/model/muscalnc)
      shell: bash
### build muscalnc from github 
    - name: checkout muscalnc main
      uses: actions/checkout@v4
      with: 
        path: muscalnc
    - name: move it to the right location
      run: (mv muscalnc $RUNNER_WORKSPACE/muscalnc/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build muscalnc as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/muscalnc/ucvm/work/model/muscalnc; ./.github/scripts/muscalnc-build-with-ucvm.sh)
      shell: bash
#    - name: Start SSH debug with tmate
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
#      with:
#        limit-access-to-actor: true
#    - name: sleep to keep runner alive
#      run: sleep 3600
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test muscalnc with ucvm
      run: (cd $RUNNER_WORKSPACE/muscalnc/ucvm/work/model/muscalnc; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/muscalnc-test-ucvm.sh)
      shell: bash
    - name: test muscalnc under ucvm
      run: (cd $RUNNER_WORKSPACE/muscalnc/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  muscalnc-build-ucvm-mac:
    if: ${{ success() }}
    needs: [muscalnc-build-ucvm-linux]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/muscalnc/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/muscalnc/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v4
      with: 
        repository: 'SCECcode/UCVM'
##        ref: testMei
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'muscalnc'
         target-model: 'muscalnc'
#   - name: Start SSH debug with upterm
#     if: ${{ failure() }}
#     uses: owenthereal/action-upterm@v1
#     with:
#         limit-access-to-actor: true
#   - name: sleep to keep runner alive
#     run: sleep 3600
    - name: get-result
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock muscalnc away
      run: (rm -rf $RUNNER_WORKSPACE/muscalnc/ucvm/work/model/muscalnc)
      shell: bash
### build muscalnc from github 
    - name: checkout muscalnc main
      uses: actions/checkout@v4
      with: 
        path: muscalnc
    - name: move it to the right location
      run: (mv muscalnc $RUNNER_WORKSPACE/muscalnc/ucvm/work/model; pwd; ls)
      shell: bash
#    - name: Start SSH debug with tmate
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
#      with:
#        limit-access-to-actor: true
#    - name: sleep to keep runner alive
#      run: sleep 3600
    - name: build muscalnc as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/muscalnc/ucvm/work/model/muscalnc; ./.github/scripts/muscalnc-build-with-ucvm.sh)
      shell: bash
#    - name: Start SSH debug with tmate
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
#      with:
#        limit-access-to-actor: true
#    - name: sleep to keep runner alive
#      run: sleep 3600
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test muscalnc with ucvm
      run: (cd $RUNNER_WORKSPACE/muscalnc/ucvm/work/model/muscalnc; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/muscalnc-test-ucvm.sh)
      shell: bash
    - name: test muscalnc under ucvm
      run: (cd $RUNNER_WORKSPACE/muscalnc/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash
#    - name: Start SSH debug with tmate
#      if: ${{ failure() }}
#      uses: mxschmitt/action-tmate@v3
#      with:
#        limit-access-to-actor: true
#    - name: sleep to keep runner alive
#      run: sleep 3600




